### PR TITLE
Updating tests and example to use Grunt 1.0.0

### PR DESCRIPTION
**Pull request by arithmetric**
After the peer dependency limit is removed in #243, this will update the tests and example to install Grunt 1.0.0 or later.

### CODE REVIEW

**Comment by arithmetric** [comment]
@grayside Without the shrinkwrap file, I got `npm install` errors when installing with Grunt 1.0.0. However if I kept the existing shrinkwrap for GDT, `npm install` did not throw any errors.

Let me know what issues you were seeing since the Grunt 1.0.0 release.

**Comment by grayside** [comment]
On the existing 0.10.1 release, I have observed the following error (screenshot courtesy of @mdeltito)
https://dl.dropboxusercontent.com/s/14ul2agfv98w50z/2016-04-06%20at%206.29%20PM.png

He tracked down https://github.com/npm/npm/issues/5135 as a potentially related issue.

**Comment by mdeltito** [comment]
@arithmetric I found that this error only occurs when pulling in GDT as a dependency, not when running `npm install` in the plugin itself. I'm testing with the following package.json:

````
{
  "name": "gdt-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "grunt": "0.4.5",
    "grunt-drupal-tasks": "0.10.1",
    "zombie": "2.5.1"
  }
}
````

Node: 4.3.1
NPM: 2.14.12

**Comment by mdeltito** [comment]
Ah, this is also currently [failing tests](https://travis-ci.org/phase2/grunt-drupal-tasks/jobs/121309580#L842).

**Comment by arithmetric** [comment]
@mdeltito I was able to reproduce the `npm install` error using your package.json. By changing the grunt version to `^1.0.0` in the package.json, I was able to run `npm install` on it without any errors.

**Comment by grayside** [comment]
I have also found this to be working if the project's package.json specifies the boosted version of grunt. Note that you need to first remove the node_modules directory otherwise the EPEERINVALID error sticks around. I think this might be a version bump for Gadget.

**Comment by mdeltito** [comment]
This is also working for me, and somehow prevents the version of Grunt inside of the GDT node_modules directory from getting bumped to 1.0.1. The project-level copy of Grunt does get updated however. This doesn't seem to cause any issues, and getting on the latest Grunt in some capacity is likely for the best, but worth noting.

**Comment by arithmetric** [comment]
Hmm... Grunt version 0.4.5 is still specified in GDT's shrinkwrap file, even though GDT's package.json has no mention of Grunt. See: https://github.com/phase2/grunt-drupal-tasks/blob/master/npm-shrinkwrap.json#L5

**Comment by mdeltito** [comment]
@arithmetric I believe this is caused by how `peerDependencies` are evaluated, and since some of the grunt plugins specify a more restrictive version identifier the GDT shrinkwrap ends up including a lower version that satisfies all peers. Bumping the parent project's version to 1.0.1 also would not affect the shrinkwrap for GDT.

**Comment by grayside** [comment]
Further discussion out-of-band, if projects have direct dependencies on grunt plugins in their package.json, the peerDependency/grunt version mismatch is still a problem.

Within GDT there are version mismatches even with this change, though at this point nothing seems to go wrong.

**Comment by arithmetric** [comment]
After further review, there are four dependencies with a peer dependency on Grunt `< 0.5` that are causing this type of error on npm install and shrinkwrap operations:
```
npm ERR! code EPEERINVALID
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
```

There are open PRs to fix each of these modules:
- https://github.com/ben-eb/grunt-available-tasks/pull/27
- https://github.com/wecodemore/grunt-githooks/pull/50
- https://github.com/grayside/grunt-notify/pull/1
- https://github.com/linusnorton/grunt-parallel-behat/pull/16

As an interim fix for GDT and Grunt 1.x compatibility, I'm adding a commit to update GDT's package.json to use git checkouts of these dependencies with the fixed configuration.

**Comment by franz-josef-kaiser** [comment]
As our project got mentioned in here: We are open for collaboration on this one, also commented on the (highly appreciated) PR. We also extended our CI setup to work with all _Nodejs_ minor and major versions from `0.10` upwards (no io.js tough) – see our [`.travis.yml` for details](https://github.com/wecodemore/grunt-githooks/blob/2875f90adab962cbc22bab749da5afab7dac3dd9/.travis.yml#L2-L11). Hope that helps.

**Comment by franz-josef-kaiser** [comment]
@arithmetric FYI, I went through the list of available Nodejs versions after finding at this repo requirements in the `README.md` (Nodejs `0.12` and `4.3`). Therefore updated our list in wecodemore/grunt-githooks#54 – This means that you will have to 

- [ ] Rebase or update your PR on our side to incorporate the changes to `.travis.yml` and file it against the `dev` branch (please)
- [ ] Update the PR here after I merged the latest changes into our `master`

Thanks for your efforts.

**Comment by arithmetric** [comment]
@franz-josef-kaiser I filed this new PR against the dev branch as you requested: https://github.com/wecodemore/grunt-githooks/pull/56

I think it includes your most recent changes, but let me know if any updates are needed. Thanks!

**Comment by franz-josef-kaiser** [comment]
After a couple _this and that_ tasks, the [`0.6.0`](https://www.npmjs.com/package/grunt-githooks/) version is now released. See #244 for additional infos. Please update your `package.json` to set the appropriate version number for `wecodemore/grunt-githooks`.

**Comment by arithmetric** [comment]
Thanks again @franz-josef-kaiser! I've updated our dependency to use `grunt-githooks ~0.6.0`.

**Pull request merged**
