### PR TITLE
Update to PHPCS 2 and Coder 8.2.6

### LINKED ISSUE #262: Switch to PHPCS 2.x and Coder 8.2.6
This gets us in-line with coding standards as they are built for both D7 and D8, and paves the way for integration with phpcbf and the DrupalPractice coding standards if we want them.

```
-    "squizlabs/php_codesniffer": "~1.5",
-    "drupal/coder": "7.2.3"
+    "squizlabs/php_codesniffer": "2.*",
+    "drupal/coder": "~8.2"
```

Change should be made both in GDT and Gadget. As far as I can tell, this is a non-breaking change and even the coding standard path in the codebase remains correct for the main Drupal standard.

### PR DESCRIPTION
**Pull request by grayside**
Fixes #262.

If this works, the same change should be applied to Gadget. I've aimed for a specific version of Coder because standards changes in the middle of a project seem in inappropriate.

### CODE REVIEW

**Comment by jhedstrom** [comment]
>  I've aimed for a specific version of Coder because standards changes in the middle of a project seem in inappropriate.

There are plenty of bugs in the checks though, so point-upgrades seem fine?

**Comment by grayside** [comment]
8.2.*? We could try that.

**Comment by grayside** [comment]
Switching to ^8.2, which is in use for Generator Gadget on D8 already.

**Comment by arithmetric** [comment]
@grayside For consistency, should php_codesniffer be changed to "^2" (and Drush to "^8" while we're at it)?

**Comment by grayside** [comment]
Updated Drush for said consistency, but pulled out PHPCS so Coder could determine the version. Roughly matches the Drupal 8 composer.json generated by Gadget.

**Comment by grayside** [comment]
The implicit PHPCS dependency pulls in 1.5 :/

**Comment by jhedstrom** [comment]
How is that possible? From coder's `composer.json`:

```json
    "require": {
        "php": ">=5.2.0",
        "squizlabs/php_codesniffer": ">=2.4.0"
    },
```

**Comment by arithmetric** [comment]
@grayside From this Travis output, it looks like it is using phpcs 2.5.1: https://travis-ci.org/phase2/grunt-drupal-tasks/jobs/119357421#L1281

**Comment by grayside** [comment]
I think I was reading the wrong travis results. This seems gtg.

**Pull request merged**
