### PR TITLE
Consolidate bundler and composer install paths and reclaim bin/ directory

### PR DESCRIPTION
**Pull request by grayside**
Takes another step on https://github.com/phase2/grunt-drupal-tasks/pull/117.

I've tested it backwards and forwards a bit, so it's looking pretty good. I seem to have a problem with grunt composer in my test environment, so let's see what Travis has to say.

### CODE REVIEW

**Comment by grayside** [comment]
Looks like Travis can't find the drush instance at vendor/bin/drush.

**Comment by arithmetric** [comment]
@grayside, I think the paths in test/test_assets/Gruntconfig.json need to be updated. See:
https://github.com/phase2/grunt-drupal-tasks/blob/feature/bundle_install_local-vendor_bin/test/test_assets/Gruntconfig.json

**Comment by grayside** [comment]
Thanks! I forgot about that one. Looks like I have a couple PRs to clean up.

**Comment by arithmetric** [comment]
This also changes the location of behat, which causes a break in behat tests. See the Travis script output:
```
stderr: 
/bin/sh: 1: ./bin/behat: not found
```

Currently the './bin/behat' path is hard-coded, so as a first step this hard-coded path can be updated. Ideally this path would be configurable like other dependencies, but that could be addressed in #102.

**Pull request merged**
